In [ ]:
import numpy as np
import pandas as pd
print(pd.__version__)
print(np.__version__)
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/Colab Databases/customers-10000.csv'
df = pd.read_csv(file_path)
df.head()

2.2.2
1.26.4
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              10000 non-null  int64
 1   Customer Id        10000 non-null  object
 2   First Name         10000 non-null  object
 3   Last Name          10000 non-null  object
 4   Company            10000 non-null  object
 5   City               10000 non-null  object
 6   Country            10000 non-null  object
 7   Phone 1            10000 non-null  object
 8   Phone 2            10000 non-null  object
 9   Email              10000 non-null  object
 10  Subscription Date  10000 non-null  object
 11  Website            10000 non-null  object
dtypes: int64(1), object(11)
memory usage: 937.6+ KB

In [ ]:
df.describe()

             Index
count  10000.00000
mean    5000.50000
std     2886.89568
min        1.00000
25%     2500.75000
50%     5000.50000
75%     7500.25000
max    10000.00000

In [ ]:
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [ ]:
df['Email']

0               urangel@espinoza-francis.net
1                    xreese@hall-donovan.com
2              haleybraun@blevins-sexton.com
3                       hohailey@anthony.com
4           alvaradojesse@rangel-shields.com
                        ...
9995               nicolasandrade@bates.info
9996                        tracy68@wade.com
9997      mclaughlinjulia@barnett-dorsey.com
9998    velazquezjessica@villegas-wilcox.com
9999                 ngallagher@martinez.com
Name: Email, Length: 10000, dtype: object